### ISSUE TITLE
Add Gas Token Price Feed Support for USD-based Cost Metrics

### ISSUE THREAD

**Issue by ijonas** [ijonas/omikuji#29]
## Overview

To enable cost tracking and analysis, we need to add support for fetching gas token prices in USD. This will allow Omikuji to provide metrics like `omikuji_cumulative_gas_cost_usd` and help operators monitor actual costs across different blockchain networks.

## Motivation

Currently, Omikuji tracks gas usage in native units (wei, gwei) but cannot provide USD-based cost metrics. This makes it difficult to:
- Monitor actual operational costs
- Compare costs across different networks
- Set budget alerts
- Generate cost reports

#### 1. Configuration Structure

**New gas price feed configuration:**
```yaml
# config.yaml
gas_price_feeds:
  enabled: true
  update_frequency: 3600  # seconds (1 hour default)
  provider: "coingecko"  # initial support for coingecko
  coingecko:
    api_key: ""  # optional, for pro API
    base_url: "https://api.coingecko.com/api/v3"
  
  # Future: support for custom providers
  # custom:
  #   ethereum:
  #     url: "https://api.example.com/prices"
  #     json_path: "$.ethereum.usd"
```

**Enhanced network configuration:**
```yaml
networks:
  - name: "ethereum"
    rpc_url: "..."
    gas_token: "ethereum"  # coingecko ID
    gas_token_symbol: "ETH"
  - name: "base"
    rpc_url: "..."
    gas_token: "ethereum"  # Base uses ETH
    gas_token_symbol: "ETH"
  - name: "bnb-smart-chain"
    rpc_url: "..."
    gas_token: "binancecoin"  # coingecko ID
    gas_token_symbol: "BNB"
```

#### 2. Module Structure

```
src/
├── gas_price/
│   ├── mod.rs              # Module exports
│   ├── models.rs           # Data structures
│   ├── fetcher.rs          # Price fetching logic
│   ├── cache.rs            # In-memory price cache
│   ├── manager.rs          # Orchestration
│   └── providers/
│       ├── mod.rs          # Provider trait
│       └── coingecko.rs    # CoinGecko implementation
```

#### 3. Core Data Structures

```rust
pub struct GasTokenPrice {
    pub token_id: String,      // e.g., "ethereum"
    pub symbol: String,        // e.g., "ETH"
    pub price_usd: f64,
    pub timestamp: u64,
    pub source: String,        // e.g., "coingecko"
}

pub trait PriceProvider: Send + Sync {
    async fn fetch_prices(&self, token_ids: &[String]) -> Result<Vec<GasTokenPrice>>;
    fn name(&self) -> &str;
}

pub struct GasPriceManager {
    providers: Vec<Box<dyn PriceProvider>>,
    cache: Arc<RwLock<PriceCache>>,
    config: GasPriceFeedConfig,
}
```

#### 1. Price Caching
- In-memory cache with configurable TTL
- Persistence to database for historical tracking
- Fallback to last known price on fetch failure
- Cache warming on startup

#### 2. Provider Support
- **Phase 1**: CoinGecko API (free & pro tiers)
- **Phase 2**: Generic JSON API support
- **Phase 3**: Multiple providers with fallback

#### 3. Database Schema
```sql
CREATE TABLE gas_token_prices (
    id SERIAL PRIMARY KEY,
    token_id VARCHAR(50) NOT NULL,
    symbol VARCHAR(10) NOT NULL,
    price_usd DECIMAL(20, 8) NOT NULL,
    source VARCHAR(50) NOT NULL,
    fetched_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_gas_prices_token_time ON gas_token_prices(token_id, fetched_at DESC);

-- For historical cost tracking
CREATE TABLE gas_costs_usd (
    id SERIAL PRIMARY KEY,
    network VARCHAR(50) NOT NULL,
    feed_name VARCHAR(100) NOT NULL,
    transaction_hash VARCHAR(66) NOT NULL,
    gas_used BIGINT NOT NULL,
    gas_price_wei NUMERIC(78, 0) NOT NULL,
    gas_token_price_usd DECIMAL(20, 8) NOT NULL,
    total_cost_usd DECIMAL(20, 8) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
```

#### 4. Enhanced Metrics
```rust
// New metrics to be added
omikuji_gas_token_price_usd         // Current price per token
  labels: [network, token_symbol]

omikuji_cumulative_gas_cost_usd     // Running total cost
  labels: [network, feed_name]

omikuji_hourly_gas_cost_usd         // Cost per hour
  labels: [network, feed_name]

omikuji_daily_gas_cost_usd          // Cost per day
  labels: [network, feed_name]

omikuji_gas_price_feed_updates_total // Price update counter
  labels: [provider, status]

omikuji_gas_price_feed_errors_total  // Error counter
  labels: [provider, error_type]

omikuji_gas_price_staleness_seconds  // Time since last update
  labels: [network, token_symbol]
```

### Error Handling & Resilience

1. **Graceful Degradation**
   - Continue operation without USD metrics if price feeds fail
   - Use cached prices with staleness warnings
   - Log but don't crash on price fetch errors

2. **Rate Limiting**
   - Respect API rate limits
   - Exponential backoff on errors
   - Request batching for efficiency

3. **Circuit Breaker**
   - Temporary disable failing providers
   - Automatic recovery attempts
   - Fallback to alternative providers

#### Basic Setup (Free Tier)
```yaml
gas_price_feeds:
  enabled: true
  update_frequency: 3600  # 1 hour
  provider: "coingecko"
```

#### Advanced Setup (Pro API with Caching)
```yaml
gas_price_feeds:
  enabled: true
  update_frequency: 300  # 5 minutes
  provider: "coingecko"
  coingecko:
    api_key: "${COINGECKO_API_KEY}"
    base_url: "https://pro-api.coingecko.com/api/v3"
  cache_ttl: 600  # 10 minutes
  fallback_to_cache: true
  persist_to_database: true
```

#### Unit Tests
- Mock provider responses
- Cache expiration and fallback
- Cost calculation accuracy
- Error handling scenarios

#### Integration Tests
- Real API calls with rate limiting
- Database persistence
- Metric updates
- Multi-network scenarios

#### Performance Tests
- High-frequency updates
- Large number of networks
- Cache efficiency
- Database query performance

#### Dashboards
- Gas costs by network and feed
- Price feed health status
- Cost trends over time
- Provider performance metrics

#### Alerts
- Price feed failures > threshold
- Unusual cost spikes (>3σ)
- Stale price data (>2x update frequency)
- Low wallet balance vs burn rate

### Security Considerations

1. **API Key Management**
   - Environment variable support
   - Integration with secret managers (#24, #26)
   - Key rotation capabilities

2. **Data Validation**
   - Sanity checks (e.g., ETH price $100-$10,000)
   - Outlier detection and filtering
   - Source verification

#### Phase 1: Basic CoinGecko Integration (MVP)
- [ ] Core data structures and traits
- [ ] CoinGecko provider implementation
- [ ] In-memory caching
- [ ] Basic metrics
- [ ] Configuration parsing

#### Phase 2: Persistence and Historical Tracking
- [ ] Database schema and migrations
- [ ] Historical cost tracking
- [ ] Cost aggregation metrics
- [ ] Price history API

#### Phase 3: Advanced Features
- [ ] Multiple provider support
- [ ] Custom JSON API provider
- [ ] Advanced caching strategies
- [ ] Cost projections and analytics

#### Phase 4: Integration and Polish
- [ ] Grafana dashboard templates
- [ ] Alert rule templates
- [ ] Documentation and examples
- [ ] Performance optimization

## Benefits

1. **Cost Visibility**: Real USD costs across all networks
2. **Budget Management**: Set alerts and track spending
3. **Optimization**: Identify high-cost feeds and networks
4. **Reporting**: Generate cost reports for stakeholders
5. **Multi-chain Comparison**: Compare costs across different blockchains

## Dependencies

- CoinGecko API (or similar price feed)
- Database for historical data
- Existing metrics infrastructure

## Related Issues

- #28 - Comprehensive Prometheus metrics (includes USD cost metrics)
- #24 - Private key security (for API key management)

## Acceptance Criteria

- [ ] Gas token prices fetched and cached successfully
- [ ] USD cost metrics exposed in Prometheus
- [ ] Historical costs persisted to database
- [ ] Graceful handling of price feed failures
- [ ] Documentation and configuration examples
- [ ] Unit and integration tests
- [ ] Performance within acceptable limits
