### ISSUE TITLE
Implement MCP Server Interface with Smart Contract Wallet Integration for AI Agent Support

### ISSUE THREAD

**Issue by ijonas** [ijonas/omikuji#30]
## Overview

Transform Omikuji into an MCP (Model Context Protocol) server that enables AI agents to interact with blockchain oracles while maintaining security through smart contract wallets with programmable spending rules. This creates a new paradigm for autonomous AI-blockchain integration.

## Vision

By combining Omikuji's oracle capabilities with:
- **MCP Server Interface**: Natural AI agent interaction with blockchain data
- **Smart Contract Wallets**: Programmable security guardrails (rate limits, spending caps)
- **Secure Key Management**: Hardware/cloud-based key isolation

We enable financially autonomous AI agents that can participate in the blockchain economy within defined safety parameters.

## Technical Architecture

```
┌─────────────┐     ┌──────────────┐     ┌─────────────────┐
│  AI Agent   │────▶│  MCP Server  │────▶│    Omikuji      │
└─────────────┘     └──────────────┘     └────────┬────────┘
                                                   │
                    ┌──────────────┐               │
                    │ Smart Wallet │◀──────────────┘
                    │  (Safe/AA)   │
                    └──────────────┘
```

### Phase 1: Secure Key Management (Prerequisites)
- [ ] Complete OS Keyring Integration (#25)
- [ ] Complete AWS Secrets Manager Support (#26)
- [ ] Optional: AWS Nitro Enclaves (#27) for high-security deployments

### Phase 2: Smart Contract Wallet Integration
- [ ] **Safe/Gnosis Safe Integration**
  - Add contract ABIs for Safe wallets
  - Implement multi-sig transaction building
  - Create spending policy encoder
- [ ] **Account Abstraction Support**
  - ERC-4337 compatible transaction building
  - Paymaster integration for gas abstraction
- [ ] **Policy Engine**
  - Daily transaction limits
  - Per-transaction USD caps (leveraging #29)
  - Contract whitelist/blacklist
  - Time-based restrictions
  - Network-specific policies

### Phase 3: MCP Server Implementation
- [ ] **Core MCP Protocol**
  - WebSocket/HTTP server for MCP connections
  - Authentication and authorization layer
  - Request routing and validation
- [ ] **Exposed Tools**
  ```typescript
  // Oracle Operations
  - read_feed_value(feed: string, network: string): FeedValue
  - get_feed_deviation(feed: string, network: string): DeviationInfo
  - request_manual_update(feed: string, network: string): UpdateResult
  
  // Cost Estimation
  - estimate_update_cost(feed: string, network: string): CostEstimate
  - get_wallet_balance(network: string): Balance
  - get_spending_limits(): SpendingPolicy
  
  // Monitoring
  - get_feed_health(feed?: string): HealthStatus[]
  - get_recent_updates(limit: number): UpdateHistory[]
  - get_agent_usage_stats(): UsageMetrics
  ```
- [ ] **Safety Controls**
  - Rate limiting per agent/API key
  - Request validation and sanitization
  - Comprehensive audit logging
  - Cost attribution and tracking

### Phase 4: Enhanced Monitoring
- [ ] Leverage Comprehensive Metrics (#28)
  - AI agent request patterns
  - Policy violation tracking
  - Cost per agent/operation
- [ ] Integrate Gas Price Feeds (#29)
  - Real-time USD cost calculations
  - Budget enforcement
  - Cost optimization recommendations

### 1. Autonomous AI Market Makers
- Monitor arbitrage opportunities across DEXs
- Execute trades within risk parameters
- Automatically rebalance portfolios

### 2. AI-Powered Prediction Markets
- Analyze data sources for predictions
- Place bets within budget constraints
- Create/resolve markets based on oracle data

### 3. Decentralized AI Service Networks
- AI agents pay each other for services
- Micro-transactions at scale
- Reputation-based service discovery

### 4. Automated DeFi Strategies
- Yield optimization across protocols
- Risk-adjusted position management
- Compound and reinvest earnings

### 5. Real-World Asset Management
- IoT sensor integration
- Automated insurance claims
- Supply chain coordination

### 6. AI Research Funding
- Evaluate proposals automatically
- Distribute milestone-based payments
- Create bounties for capabilities

### Multi-Layer Security Model
1. **Key Security**: Hardware enclaves or cloud KMS
2. **Transaction Security**: Smart contract wallets with policies
3. **API Security**: Authentication, rate limiting, audit trails
4. **Economic Security**: Spending caps, gradual trust building

### Policy Examples
```yaml
policies:
  daily_transaction_limit: 100
  max_usd_per_transaction: 1000
  max_gas_price_gwei: 200
  allowed_contracts:
    - "0x..." # Uniswap Router
    - "0x..." # Aave Lending Pool
  time_restrictions:
    - no_transactions_between: "00:00-06:00 UTC"
```

## Configuration Example

```yaml
mcp_server:
  enabled: true
  port: 8545
  authentication:
    type: "api_key"
    keys:
      - name: "trading_agent"
        key: "${TRADING_AGENT_API_KEY}"
        policies:
          daily_limit_usd: 10000
          per_tx_limit_usd: 500
      - name: "research_agent"
        key: "${RESEARCH_AGENT_API_KEY}"
        policies:
          daily_limit_usd: 100
          read_only: true
  
smart_wallets:
  - network: "ethereum"
    type: "safe"
    address: "0x..."
    threshold: 2
    owners:
      - "${OMIKUJI_SIGNER_ADDRESS}"
      - "${BACKUP_SIGNER_ADDRESS}"
  - network: "base"
    type: "account_abstraction"
    factory: "0x..."
    paymaster: "0x..."
```

## Success Criteria

- [ ] AI agents can read oracle data via MCP
- [ ] AI agents can trigger oracle updates within limits
- [ ] All transactions go through smart contract wallets
- [ ] Spending policies are enforced on-chain
- [ ] Comprehensive audit trail of all operations
- [ ] No single point of failure for funds
- [ ] Performance: <100ms latency for read operations
- [ ] Scale: Support 100+ concurrent AI agents

## Dependencies

- #25 - OS Keyring Integration (security foundation)
- #26 - AWS Secrets Manager Support (cloud key management)
- #27 - AWS Nitro Enclaves (optional high security)
- #28 - Comprehensive Prometheus Metrics (monitoring)
- #29 - Gas Token Price Feeds (USD cost tracking)

## Future Enhancements

1. **Cross-chain Operations**: Enable AI agents to work across multiple chains
2. **MEV Protection**: Integrate with Flashbots for private transactions
3. **AI Model Verification**: Prove which AI model made decisions
4. **Decentralized MCP**: Multiple Omikuji instances with consensus

## References

- [MCP Protocol Specification](https://modelcontextprotocol.io/docs)
- [Safe Smart Wallet Docs](https://docs.safe.global)
- [ERC-4337 Account Abstraction](https://eips.ethereum.org/EIPS/eip-4337)

This integration represents a fundamental shift in how AI agents can interact with blockchain systems, enabling true autonomous economic agents with built-in safety mechanisms.
